[project]
name = "report-portal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "reportportal-client>=5.6.4",
]

[tool.poetry.dependencies]
python = "^3.11"
reportportal-client= "^5.6.4"
